# Generated by Django 3.2.8 on 2021-10-24 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9000)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='thumb.jpg', upload_to='post/thumb/')),
                ('Title', models.CharField(max_length=9000)),
                ('intro', models.TextField(blank=True, default=None, verbose_name='introduction')),
                ('body', models.TextField(blank=True, default=None, verbose_name='content')),
                ('v_link', models.TextField(blank=True, default=None, verbose_name='video link')),
                ('m_link', models.TextField(blank=True, default=None, verbose_name='music link')),
                ('s_link', models.TextField(blank=True, default=None, verbose_name='social link')),
                ('slug', models.SlugField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cre.category', verbose_name='category')),
            ],
        ),
    ]
