# Generated by Django 3.2.8 on 2021-10-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Title',
        ),
        migrations.AddField(
            model_name='article',
            name='l_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='stamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=9000),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='profile.jpg', upload_to='post/thumb/')),
                ('About', models.TextField(blank=True, default=None, verbose_name='content')),
                ('phone', models.CharField(max_length=15)),
                ('s_link', models.TextField(blank=True, default=None, verbose_name='instagram')),
                ('slug', models.SlugField(default=None)),
                ('l_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
