# Generated by Django 3.2.8 on 2021-10-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cre', '0002_auto_20211024_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='l_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
