# Generated by Django 3.2.8 on 2021-10-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cre', '0003_category_l_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload',
            field=models.FileField(blank=True, upload_to='post/upload/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='cre.profile'),
        ),
    ]
